[workspace] 
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64" ]
preview = ["pixi-build"]

[dependencies] 
information-sheet-problem = { path = "." }

# [tasks] 
# start = "rich-example-main"

[package] 
name = "information-sheet-problem"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies] 
# rich = "13.9.*"
